apiVersion: ipam.netbox.natzkalabs.com/v1alpha1
kind: Prefix
metadata:
  annotations:
    meta.upbound.io/example-id: ipam/v1alpha1/prefix
  labels:
    testing.upbound.io/example-name: my_prefix
  name: my-prefix
spec:
  forProvider:
    description: test prefix
    prefix: 10.0.0.0/24
    status: active
